<?php
$text=array("Only 2 things can change women’s mood- 1) I love you, 2) 50% Discount!!",
"Only 2 things can change women’s mood- 1) I love you, 2) 50% Discount!!",
"Only 2 things can change women’s mood- 1) I love you, 2) 50% Discount!!",
"Bol rahi thi i don’t love you, Pyar mein dhokha isliye Thokaaa…",
"Bol rahi thi i don’t love you, Pyar mein dhokha isliye Thokaaa…",
"Sugar? No thanks, i am already sweet..",
"Every love story is beautiful, But ours is My Favorite!",
"Falling in Love is easy…But staying in Love is very special…",
"Rose is red, sky is blue, my love is true only for you.",
"Love doesn’t need a reason. Pure Love will come from the heart without reason. And stay every season.",
"Love doesn’t need to be perfect.It needs to be true.",
"Love is the other NAME Of Respect, if you can’t Respect your loved One then you don’t deserve to be loved.",
"Love looks not with the eyes, but with the mind.",
"I can’t promise to fix all your problems, but i promise you won’t face them alone.",
"You are my best reason to lose sleep.",
            "I am in love with you and all your little things..",
         "The person who truly loves you will never let you go whatever the situation is.",
      "Love is friendship Set on Fire",
         "I just want to be your favorite Hello, and Hardest goodbye.",
            "Am i just crazy or falling in love?",
"Love is what your heart feels, not what your mind thinks.",
"The moment i saw you, i fell in love & you smiled because you knew.",
"Every time i see the keyboard, i always see U & I together.",
"Every time i see the keyboard, i always see U & I together.",
"Every time i see the keyboard, i always see U & I together.",
"The true love is that changes you into a better person without changing you to someone else.",
"I would love to stay awake just to watch you Sleep.",
"Being with you has made me 100% complete..",
"Kiss me, & You will see stars, Love me and i will give them to you…",
"Love is life, & if you miss life, You miss Love.",
"We loved with a love which was more then Love.."
"My  6  words  love story  – I can’t imagine Life without you.",
"Every  time  i s ee you I fall in love all over again.",
"Every time i see you I fall in love all over again.",
"My heart is and always be yours forever.",
"I know I’m not perfect, I’m vintage, which means my flaws make me priceless!",
"Congratulations!!My tallest finger want to give you a standing ovation.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"You don’t need a reason to help people.",
"If i treated you the way you trated me, you would hate me.",
"My playlist can tell you the story of my life.",
"You best teacher is the mistake you made in past.",
"Dreams Don’t work unless you do.",
"A simple hello could lead to million things.",
"Life is short, smile till you still have teeth.",
"I am sad, but then i smile. That’s my life.",
"Sometimes we just have to let things go.",
"Only regret left at the end is the Chances we didn’t take.",
"Silence is the most loud voice.",
"With the change in seasons,people change people from their life",
"Love the life you live, and live the life you love.",
"lovely photo",
"i like your photo",
"Good Editing Of your Photo",
"Nice photo   ..Love the life you live, and live the life you love.",
"Good Loook .. Love the life you live, and live the life you love.",
"Life is not about finding yourself. Life is about creating yourself.",
"If you want to live a happy life, tie it to a goal, not to people or things.",
"I’ve learned if you love life, life will love you back sooner or later.",
"The quality of your life is the quality of your relationships.",
"Life goes on……With or without you ",
"Everyone comes in our life for a reason. Those who don’t have any, stay.",
"Life will always try to make things hard, but every time you overcome those obstacles, you becomes stronger.",
"Life is a story, Make yours the best seller!",
"The best way to let people remember you is to ‘borrow money from them",
"If you’re wondering why you’re single, date someone. You’ll remember",
"The voices in my head are not real, but they have good ideas.",
"You can’t make everyone happy, so today I think you should focus on me.",
"The reason good men are hard to find is because they’re usually too busy working.",
"I should win an Oscar for acting like I’m busy at work.",
"I always dream of being a millionaire like my uncle!… He’s dreaming too.",
"Maths and women are the two most complicated things in this World. BUT… Maths, Atleast, has LOGIC",

);
?>